version: "3.8"
services:
  app:
    build: .
    environment:
      DB_HOST: db
      DB_DATABASE: tasks
      DB_USERNAME: sasha
      DB_PASSWORD: secret
    volumes:
      - ./:/var/www/html
    networks:
      - app-network
    depends_on:
      - db
    

  webserver:
    image: nginx:alpine
    ports:
      - "80:80"  
    volumes:
      - ./:/var/www/html
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: postgres
    environment:
      POSTGRES_DB: tasks
      POSTGRES_USER: sasha
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/postgresql/data


networks:
  app-network:
    driver: bridge

volumes:
  db_data:
